import { FileSearch } from "lucide-react";
import type { DecisionReceipt, StoryCard } from "@/lib/types";
import { nullableScore, percentText } from "@/lib/format";
import VerdictCard from "./VerdictCard";
import { DetailCell, Disclosure, ListBlock, RawJson, SourceLink, Warnings } from "./Fragments";

interface ReceiptDetailProps {
  receipt: DecisionReceipt | null;
  card: StoryCard | undefined;
}

export default function ReceiptDetail({ receipt, card }: ReceiptDetailProps) {
  const title = receipt
    ? `${receipt.symbol} ${receipt.signal || receipt.verdict?.decision || "receipt"}`
    : "Decision receipt";

  return (
    <section className="receipt-panel" aria-label="Decision receipt">
      <div className="panel-heading compact">
        <div>
          <p className="eyebrow">Replayable receipt</p>
          <h2>{title}</h2>
        </div>
        <FileSearch aria-hidden="true" />
      </div>

      <div className="receipt-detail">
        {!receipt ? (
          <div className="empty-state compact-empty">
            <FileSearch aria-hidden="true" />
            <strong>No receipt selected</strong>
            <span>Decision evidence will appear here.</span>
          </div>
        ) : (
          <div className="receipt-summary">
            <VerdictCard receipt={receipt} />
            <Warnings warnings={receipt.warnings} />

            <Disclosure title="Decision evidence" meta="4 sections" open>
              <ListBlock label="Why it matters" items={receipt.verdict?.why_it_matters} />
              <ListBlock label="Top global news" items={receipt.verdict?.top_global_news} />
              <ListBlock label="RYO market evidence" items={receipt.verdict?.ryo_market_evidence} />
              <ListBlock
                label="Missing data"
                items={receipt.reasoning_layer?.unavailable_data || receipt.verdict?.missing_data}
              />
            </Disclosure>

            {card ? (
              <Disclosure title="Selected story analysis" meta={`Impact ${card.score.impact}`}>
                <CardBreakdown receipt={receipt} card={card} />
              </Disclosure>
            ) : null}

            <Disclosure title="Receipt metadata" meta={receipt.run_id.slice(0, 8)}>
              <div className="detail-grid">
                <DetailCell label="Run ID" value={receipt.run_id} />
                <DetailCell label="Created" value={receipt.created_at} />
                <DetailCell label="Timeframe" value={receipt.timeframe} />
                <DetailCell label="Generated by" value={receipt.verdict?.generated_by || "pending"} />
              </div>
            </Disclosure>

            <RawJson receipt={receipt} />
          </div>
        )}
      </div>
    </section>
  );
}

function CardBreakdown({ receipt, card }: { receipt: DecisionReceipt; card: StoryCard }) {
  return (
    <div className="card-breakdown">
      <div>
        <h3>{card.headline}</h3>
        <p>{receipt.summary.conclusion}</p>
      </div>
      <div className="detail-grid">
        <DetailCell label="Recommendation" value={card.recommendation} />
        <DetailCell label="Confidence" value={card.confidence} />
        <DetailCell label="Sentiment" value={card.sentiment} />
        <DetailCell label="Cluster" value={card.narrative_cluster} />
        <DetailCell label="Source" value={card.source} />
        <DetailCell label="Receipt confidence" value={percentText(receipt.confidence)} />
      </div>
      <ListBlock label="Reasoning" items={card.reasoning} />
      <div className="detail-grid score-detail-grid">
        <DetailCell label="Impact" value={card.score.impact} />
        <DetailCell label="Relevance" value={nullableScore(card.score.relevance)} />
        <DetailCell label="Credibility" value={nullableScore(card.score.credibility)} />
        <DetailCell label="Urgency" value={nullableScore(card.score.urgency)} />
        <DetailCell label="Market confirm" value={nullableScore(card.score.market_confirmation)} />
        <DetailCell label="Uncertainty" value={nullableScore(card.score.uncertainty)} />
      </div>
      <SourceLink card={card} />
    </div>
  );
}
