import type { DecisionReceipt } from "@/lib/types";
import { percentNumber } from "@/lib/format";
import { DetailCell, ListBlock } from "./Fragments";

export default function VerdictCard({ receipt }: { receipt: DecisionReceipt }) {
  const verdict = receipt.verdict;
  const layer = receipt.reasoning_layer;
  return (
    <article className="verdict-card">
      <div className="verdict-top">
        <div>
          <p className="eyebrow">RYO-CHAN reasoning layer</p>
          <h3>{layer?.signal || receipt.signal || verdict?.decision || "PENDING"}</h3>
        </div>
        <div className="confidence-dial">
          <strong>{percentNumber(layer?.confidence ?? receipt.confidence ?? verdict?.confidence)}</strong>
          <span>confidence</span>
        </div>
      </div>
      <div className="detail-grid">
        <DetailCell label="Token" value={layer?.symbol || verdict?.token_symbol || receipt.symbol} />
        <DetailCell label="Market confirm" value={layer?.market_confirmation || "-"} />
        <DetailCell label="Sentiment" value={layer?.sentiment || "-"} />
        <DetailCell label="Tools used" value={(layer?.ryo_tools_used || receipt.ryo_tools_used || []).join(", ")} />
        <DetailCell label="Generated by" value={verdict?.generated_by || "pending"} />
        <DetailCell label="Next action" value={layer?.next_action || verdict?.recommended_next_action || "-"} />
        <DetailCell label="Replay ID" value={layer?.run_id || receipt.run_id} />
      </div>
      <div>
        <p className="eyebrow">Reasoning</p>
        <p>{layer?.reasoning || receipt.reasoning || "No reasoning returned yet."}</p>
      </div>
      <ListBlock label="Why it matters" items={verdict?.why_it_matters} />
      <ListBlock label="Top global news" items={verdict?.top_global_news} />
      <ListBlock label="RYO market evidence" items={verdict?.ryo_market_evidence} />
      <ListBlock label="Missing data" items={layer?.unavailable_data || verdict?.missing_data} />
    </article>
  );
}
