// The verdict card: the RYO-CHAN reasoning-layer summary block.

import { escapeHtml } from "../core/dom.js";
import { percentNumber } from "../core/format.js";
import { detailCell, listBlock } from "./fragments.js";

/** Build the verdict card HTML for a receipt. */
export function verdictBlock(receipt) {
  const verdict = receipt.verdict || {};
  const layer = receipt.reasoning_layer || {};
  return `
    <article class="verdict-card">
      <div class="verdict-top">
        <div>
          <p class="eyebrow">RYO-CHAN reasoning layer</p>
          <h3>${escapeHtml(layer.signal || receipt.signal || verdict.decision || "PENDING")}</h3>
        </div>
        <div class="confidence-dial">
          <strong>${escapeHtml(percentNumber(layer.confidence ?? receipt.confidence ?? verdict.confidence))}</strong>
          <span>confidence</span>
        </div>
      </div>
      <div class="detail-grid">
        ${detailCell("Token", layer.symbol || verdict.token_symbol || receipt.symbol)}
        ${detailCell("Market confirm", layer.market_confirmation || "-")}
        ${detailCell("Sentiment", layer.sentiment || "-")}
        ${detailCell("Tools used", (layer.ryo_tools_used || receipt.ryo_tools_used || []).join(", "))}
        ${detailCell("Generated by", verdict.generated_by || "pending")}
        ${detailCell("Next action", layer.next_action || verdict.recommended_next_action || "-")}
        ${detailCell("Replay ID", layer.run_id || receipt.run_id)}
      </div>
      <div>
        <p class="eyebrow">Reasoning</p>
        <p>${escapeHtml(layer.reasoning || receipt.reasoning || "No reasoning returned yet.")}</p>
      </div>
      ${listBlock("Why it matters", verdict.why_it_matters)}
      ${listBlock("Top global news", verdict.top_global_news)}
      ${listBlock("RYO market evidence", verdict.ryo_market_evidence)}
      ${listBlock("Missing data", layer.unavailable_data || verdict.missing_data)}
    </article>
  `;
}
